use std::env;
use std::fs::{self, File};
use std::io::{BufReader, Read};
use std::path::{Path, PathBuf};

const FNV_OFFSET_BASIS: u64 = 0xcbf29ce484222325;
const FNV_PRIME: u64 = 0x100000001b3;

fn main() {
    const ICON_PATH: &str = "assets/branding/Insta360Linker.ico";

    println!("cargo:rerun-if-changed={ICON_PATH}");
    println!("cargo:rerun-if-changed=assets/apk_watermark");
    println!("cargo:rerun-if-env-changed=INSTA360LINKER_WINDOWS_FFMPEG_PATH");
    println!("cargo:rerun-if-env-changed=INSTA360LINKER_WINDOWS_FFMPEG_LICENSE_PATH");
    println!("cargo:rerun-if-env-changed=INSTA360LINKER_WINDOWS_VCAM_DLL_PATH");

    let target_is_windows = env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows");
    generate_embedded_windows_resources(target_is_windows)
        .expect("failed to generate embedded Windows resources");

    if !target_is_windows {
        return;
    }

    let mut resource = winresource::WindowsResource::new();
    resource
        .set_icon(ICON_PATH)
        .set("ProductName", "Insta360Linker")
        .set("FileDescription", "Insta360Linker")
        .set("InternalName", "Insta360Linker")
        .set("OriginalFilename", "Insta360Linker.exe");
    resource
        .compile()
        .expect("failed to compile the Insta360Linker Windows resources");
}

fn generate_embedded_windows_resources(target_is_windows: bool) -> std::io::Result<()> {
    let output = PathBuf::from(env::var_os("OUT_DIR").expect("Cargo did not provide OUT_DIR"))
        .join("embedded_windows_resources.rs");
    let ffmpeg = configured_resource("INSTA360LINKER_WINDOWS_FFMPEG_PATH", target_is_windows)?;
    let virtual_camera =
        configured_resource("INSTA360LINKER_WINDOWS_VCAM_DLL_PATH", target_is_windows)?;
    let ffmpeg_license = configured_path(
        "INSTA360LINKER_WINDOWS_FFMPEG_LICENSE_PATH",
        target_is_windows,
    )?;
    let watermark_assets = if target_is_windows {
        watermark_assets(Path::new("assets/apk_watermark"))?
    } else {
        Vec::new()
    };

    let mut generated = String::from(
        "// Generated by build.rs. Do not edit.\n\
         pub const EMBEDDED_WINDOWS_WATERMARK_COUNT: usize = ",
    );
    generated.push_str(&watermark_assets.len().to_string());
    generated.push_str(";\n");
    write_resource_constants(&mut generated, "FFMPEG", ffmpeg.as_ref(), "ffmpeg", "exe");
    write_resource_constants(
        &mut generated,
        "VIRTUAL_CAMERA_DLL",
        virtual_camera.as_ref(),
        "virtual-camera",
        "dll",
    );
    match ffmpeg_license {
        Some(path) => generated.push_str(&format!(
            "pub const EMBEDDED_WINDOWS_FFMPEG_LICENSE: Option<&'static str> = Some(include_str!({:?}));\n",
            path.to_string_lossy()
        )),
        None => generated.push_str(
            "pub const EMBEDDED_WINDOWS_FFMPEG_LICENSE: Option<&'static str> = None;\n",
        ),
    }
    generated.push_str(
        "pub fn embedded_windows_watermark(file: &str) -> Option<&'static [u8]> {\n    match file {\n",
    );
    for (name, path) in watermark_assets {
        generated.push_str(&format!(
            "        {:?} => Some(include_bytes!({:?})),\n",
            name,
            path.to_string_lossy()
        ));
    }
    generated.push_str("        _ => None,\n    }\n}\n");

    fs::write(output, generated)
}

struct EmbeddedResource {
    path: PathBuf,
    hash: u64,
}

fn configured_resource(
    variable: &str,
    target_is_windows: bool,
) -> std::io::Result<Option<EmbeddedResource>> {
    let Some(path) = configured_path(variable, target_is_windows)? else {
        return Ok(None);
    };
    Ok(Some(EmbeddedResource {
        hash: fnv1a_file(&path)?,
        path,
    }))
}

fn configured_path(variable: &str, target_is_windows: bool) -> std::io::Result<Option<PathBuf>> {
    if !target_is_windows {
        return Ok(None);
    }
    let Some(value) = env::var_os(variable) else {
        return Ok(None);
    };
    let path = fs::canonicalize(PathBuf::from(value))?;
    println!("cargo:rerun-if-changed={}", path.display());
    Ok(Some(path))
}

fn write_resource_constants(
    generated: &mut String,
    constant: &str,
    resource: Option<&EmbeddedResource>,
    filename_prefix: &str,
    extension: &str,
) {
    match resource {
        Some(resource) => {
            generated.push_str(&format!(
                "pub const EMBEDDED_WINDOWS_{constant}: Option<&'static [u8]> = Some(include_bytes!({:?}));\n",
                resource.path.to_string_lossy()
            ));
            generated.push_str(&format!(
                "pub const EMBEDDED_WINDOWS_{constant}_HASH: u64 = 0x{:016x};\n",
                resource.hash
            ));
            generated.push_str(&format!(
                "pub const EMBEDDED_WINDOWS_{constant}_FILENAME: &str = {:?};\n",
                format!("{filename_prefix}-{:016x}.{extension}", resource.hash)
            ));
        }
        None => {
            generated.push_str(&format!(
                "pub const EMBEDDED_WINDOWS_{constant}: Option<&'static [u8]> = None;\n"
            ));
            generated.push_str(&format!(
                "pub const EMBEDDED_WINDOWS_{constant}_HASH: u64 = 0;\n"
            ));
            generated.push_str(&format!(
                "pub const EMBEDDED_WINDOWS_{constant}_FILENAME: &str = \"\";\n"
            ));
        }
    }
}

fn watermark_assets(root: &Path) -> std::io::Result<Vec<(String, PathBuf)>> {
    let mut assets = Vec::new();
    for entry in fs::read_dir(root)? {
        let entry = entry?;
        let path = entry.path();
        if !path.is_file() || path.extension().and_then(|value| value.to_str()) != Some("png") {
            continue;
        }
        println!("cargo:rerun-if-changed={}", path.display());
        let name = entry.file_name().to_string_lossy().into_owned();
        assets.push((name, fs::canonicalize(path)?));
    }
    assets.sort_by(|left, right| left.0.cmp(&right.0));
    Ok(assets)
}

fn fnv1a_file(path: &Path) -> std::io::Result<u64> {
    let mut reader = BufReader::new(File::open(path)?);
    let mut buffer = [0u8; 64 * 1024];
    let mut hash = FNV_OFFSET_BASIS;
    loop {
        let read = reader.read(&mut buffer)?;
        if read == 0 {
            break;
        }
        for byte in &buffer[..read] {
            hash ^= u64::from(*byte);
            hash = hash.wrapping_mul(FNV_PRIME);
        }
    }
    Ok(hash)
}
